version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: task_management
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_NAME: task_management
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
      JWT_SECRET: your_secret_key
      PORT: 3000
    depends_on:
      - db

volumes:
  pgdata:
